#!/usr/bin/sh
RED='\033[0;31m'
NC='\033[0m' # No Color
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1
make
./tests/tests
if [[ ! -z $(./tests/tests | grep -m 1 'FAIL!') ]]; then
        echo -e "$RED No Commit tests FAIL...$NC"
        exit 1
fi
