#!/bin/sh

# "$(dirname "$0")"/pre-commit-formating
# if [ $? -eq 0 ]; then
# echo "formating OK"
# else
# exit 1
# fi
#
"$(dirname "$0")"/pre-commit-tests
if [ $? -eq 0 ]; then
echo "tests OK"
else
exit 1
fi
#
# "$(dirname "$0")"/pre-commit-generation-doxygen
# if [ $? -eq 0 ]; then
# echo "doxygen OK"
# else
# exit 1
# fi
