#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

CLANG_FORMAT="clang-format-diff -p1 -v -sort-includes -style=LLVM -iregex '.*\.(cxx|cpp|hpp|h)$' "
GIT_DIFF="git diff -U0 --no-color "
GIT_APPLY="git apply -v -p0 - "
FORMATTER_DIFF=$(eval ${GIT_DIFF} --staged | eval ${CLANG_FORMAT})

echo -e "\n$GREEN------Format code hook is called-------$NC"

if [ -z "${FORMATTER_DIFF}" ]; then
	echo "Nothing to be formatted"
else
	echo "${FORMATTER_DIFF}"
	echo "${FORMATTER_DIFF}" | eval ${GIT_APPLY} --cached
	echo "      ---Format of staged area completed. Begin format unstaged files---"
	eval ${GIT_DIFF} | eval ${CLANG_FORMAT} | eval ${GIT_APPLY}
fi

echo -e "$GREEN------Format code hook is completed----$NC\n"
exit 0
